name = "nightingale-agent-discovery"
main = "agent-discovery.js"
compatibility_date = "2024-01-01"

# routes = [
#   { pattern = "nightingale-security.com/*", zone_name = "nightingale-security.com" }
# ]
